# PureKitPvP by LifelessNerd
# Partially based on PureKits
# 2022

# World in which the plugin should be active: i.e. kits, deaths, stats and such
world: pvp
# Y level at which you should die in pvp, please provide double
voidY: 0.0
#respawn X, Y, Z in world
respawnX: 0.5
respawnY: 142.0
respawnZ: 0.5