# PureKitPvP by LifelessNerd
# Partially based on PureKits
# 2022

# World in which the plugin should be active: i.e. kits, deaths, stats and such
world: pvp
# Y level at which you should die in pvp, please provide double
voidY: 0.0